### ISSUE TITLE
V1.4 Review for Collated code

### ISSUE THREAD

**Issue by tshradheya** [CS2103JAN2018-W10-B3/main#127]
@jaxony Code review for you.

My comments are below the picture.

1. 
![image](https://user-images.githubusercontent.com/12574756/38550199-600142c0-3ce8-11e8-9680-3244cd681c43.png)

Avoid writing comments inside the function. Header comment should explain everything.

2. 
![image](https://user-images.githubusercontent.com/12574756/38550234-7be6278a-3ce8-11e8-9599-8b75a50f7d3d.png)

![image](https://user-images.githubusercontent.com/12574756/38550508-4ab5d38a-3ce9-11e8-87df-35823160e615.png)

`Create` -> `Creates` The first word of header comment should be in imperative form. E.g. `Adds` , `Raises event`

3. 
![image](https://user-images.githubusercontent.com/12574756/38550310-b3492f9c-3ce8-11e8-80f1-ae8daace3f54.png)

Please make sure the collated tags are properly made

4. 
![image](https://user-images.githubusercontent.com/12574756/38550341-d0d68906-3ce8-11e8-9e87-f6a76672b540.png)
Rename to `foodToAdd` ?

5. 
![image](https://user-images.githubusercontent.com/12574756/38550387-fbff9618-3ce8-11e8-8d43-a0c238fa7521.png)

Why `Class` ? Shouldn't it be `Field` ?

6. 
![image](https://user-images.githubusercontent.com/12574756/38550529-5a862b7a-3ce9-11e8-9772-5e723ab9391f.png)

Magic numbers? Applicable in other places

**Comment by jaxony** [comment]
closed via #158
