### ISSUE TITLE
V1.4 Code Review

### ISSUE THREAD

**Issue by tshradheya** [CS2103JAN2018-W10-B3/main#128]
@samzx For you

1. 
![image](https://user-images.githubusercontent.com/12574756/38550747-ec341af0-3ce9-11e8-9575-5c6bcbf008bd.png)

Comment should be like this `Displays price`. First word of header comment should be in imperative form. For e.g. `Adds` , `Creates`, `Shows` etc

Read up on https://oss-generic.github.io/process/codingStandards/CodingStandard-Java.html the coding standards

Note: Please collate properly. I am sure you have written more than this much 😆 
Feel free to ping me once you are done

**Comment by samzx** [comment]
@tshradheya the latest version v1.5rc should have the collated code now 👍
