### ISSUE TITLE
Add command, press enter to skip optional fields

### ISSUE THREAD

**Issue by samzx** [CS2103JAN2018-W10-B3/main#143]
@jaxony 

Could we make it that we can skip optional fields such as email and address. Pressing enter will simply fill in the field as the default field ie. filling 

- `Email.DEFAULT_EMAIL`
- `Address.DEFAULT_ADDRESS`
- `Price.DEFAULT_PRICE`
- `Rating.DEFAULT.RATING`

**Comment by jaxony** [comment]
resolved via #157
