### ISSUE TITLE
Update documentation: Developer guide

### ISSUE THREAD

**Issue by tohcheryl** [CS2103JAN2018-W10-B3/main#30]
Developer Guide:

Each member should describe the implementation of at least one enhancement she has added (or planning to add). 
Expected length: 1+ page per person
The description can contain things such as,
How the feature is implemented.
Why it is implemented that way.
Alternatives considered.
The stated objective is to explain the implementation to a future developer, but a hidden objective is to show evidence that you can document deeply-technical content using prose, examples, diagrams, code snippets, etc. appropriately. To that end, you may also describe features that you plan to implement in the future, even beyond v1.5 (hypothetically).
For an example, see the description of the undo/redo feature implementation in the AddressBook-Level4 developer guide.

**Comment by samzx** [comment]
From lecture:

Indicate features in Dev Guide

- Dev Guide -> Appendix B -> Feature contribution
- One two lines summary of how it fits in the project
- Identify what's major, what's minor

**Comment by samzx** [comment]
Created seperate issue for order command developer guide #46 
Unassigned myself to this issue.

**Comment by tohcheryl** [comment]
Created separate issues for making shortcuts #47 and Food Profile #48 
Unassigned everyone
