### ISSUE TITLE
v1.2 Demo

### ISSUE THREAD

**Issue by tohcheryl** [CS2103JAN2018-W10-B3/main#31]
v1.2 Demo
Do an informal demo of the new feature during the tutorial. Each team member should demo their own work, using commit tagged as v1.2 in the master branch  i.e. only features included in the current release should be demoed.

**Comment by samzx** [comment]
Features included for v1.2:
#40 
#41 
#44

**Comment by samzx** [comment]
closed as now is duplicate.
