### ISSUE TITLE
Known bugs

### ISSUE THREAD

**Issue by jaxony** [CS2103JAN2018-W10-B3/main#94]
- cannot submit 0 tags / allergies in interactive `add` (@jaxony)
- missing information for allergies (i.e., [alg/ALLERGY]) when ParseException is raised (@tohcheryl)
- error of ParseException in interactive `add` is not error style (@jaxony)

**Comment by jaxony** [comment]
Bugs addressed in other issues.

**Comment by tohcheryl** [comment]
What's the missing information for allergies about?

**Comment by jaxony** [comment]
@tohcheryl when `add` is an invalid command, e.g. `add n/`, the error message doesn't include [alg/ALLERGY] (I think you fixed this already? May be wrong)
